name: attedance_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  footer: ^0.0.4
  cached_network_image: ^3.4.1
  http: ^1.4.0
  network_info_plus: ^6.1.1
  provider: ^6.1.2
  intl: ^0.18.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.1.5
  firebase_messaging_web: ^3.9.4
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  share_plus: ^10.1.4
  path: ^1.9.0
  image_picker: ^1.1.2
  kakao_flutter_sdk_user: ^1.9.7+3
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.4.2
  marquee: ^2.3.0
  flutter_svg: ^2.1.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  bootpay: ^5.0.13
  flutter_launcher_icons: ^0.14.4
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

dependency_overrides:
  js: 0.6.4
  uuid: ^3.0.7
  intl: ^0.18.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/icons/app_icon.png
    - assets/icons/google_icon.png
    - assets/icons/kakao_icon.png
    - assets/icons/apple_icon.png
    - assets/icons/apple_icon.svg
    - assets/icons/kakao_icon.svg
    - assets/icons/google_icon.svg
    - assets/icons/app_logo.svg
    - assets/icons/app_logo.png
    - assets/icons/splash_logo.png
    - assets/icons/smartphone.svg
    - assets/icons/footer_icons/home_icon.svg
    - assets/icons/footer_icons/inbox_icon.svg
    - assets/icons/footer_icons/boxButton_icon.svg
    - assets/icons/footer_icons/trophy_icon.svg
    - assets/icons/footer_icons/user-round_icon.svg
    - assets/icons/profile_icons/profile_coupon_icon.svg
    - assets/icons/profile_icons/profile_friend_icon.svg
    - assets/icons/profile_icons/profile_gift_icon.svg
    - assets/icons/profile_icons/profile_point_icon.svg
    - assets/icons/profile_icons/profile_setting_icon.svg
    - assets/icons/profile_icons/profile_shipping_icon.svg

    - assets/images/EndOfScreen.png
    - assets/images/BoxEmptyStateImage.png
    - assets/images/order_box_image.png
    - assets/images/present_image.png
    - assets/images/coupon_code_image.png
    - assets/images/shipping_missing.png
    - assets/images/ErrorImage.svg
    - assets/images/ranking_images/unboxing_high.png
    - assets/images/ranking_images/unboxing_max.png
    - assets/images/ranking_images/unboxing_try.png


    - assets/videos/boxOpen_video.mp4
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
